# Generated by Django 4.2.3 on 2023-08-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hours_of_operation',
            field=models.CharField(default='varies', max_length=200),
        ),
    ]
