# Generated by Django 4.2.3 on 2023-08-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_doctor_hours_of_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hours_of_operation',
        ),
        migrations.AddField(
            model_name='doctor',
            name='user_id',
            field=models.IntegerField(default='1'),
        ),
    ]
