# Generated by Django 4.2.3 on 2023-08-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_doctor_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='choice_field',
            field=models.CharField(choices=[('general_physian', 'General Physician'), ('orthopatic', 'Orthopatic'), ('Sergion', 'Sergion')], default='general_physian', max_length=20),
        ),
    ]
