# Generated by Django 4.2.3 on 2023-08-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_appointment_doctor_alter_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('ongoing', 'On Going'), ('patient_not_arrived', 'Patient Not Arrived'), ('doctor_not_arrived', 'Doctor Not Arrived'), ('both_not_arrived', 'Both Not Arrived'), ('went_well', 'Went Well')], default='pending_approval', max_length=20),
        ),
    ]
